### ISSUE TITLE
Best practice for finding closest matches within a corpus

### ISSUE THREAD

**Issue by grofte** [x-tabdeveloping/neofuzz#1]
I have a corpus.
For each string in the corpus I want to find its closest string(s).
Should I simply create the index and loop over the corpus?
Or does this still count as only having a few lookups to perform?

Is there a better way than looping?
Maybe accessing the index directly in some way or vectorizing the lookup method?

**Comment by x-tabdeveloping** [comment]
neofuzz Processes have a `.query()` method, that you could potentially use for this.
If you have an indexed process with a given list of texts you want to get the nearest neighbours of this is how you would do it.
```python
# this is your list of texts:
texts: list[str] = [...]
process.index(texts)
# Then query with all texts at once:
indices, distances = process.query(texts, limit=10)
```
Here `indices` is a matrix of the indices of nearest neighbours for each of the search terms.
So for example the  indices of the 10 nearest neighbours of the first term is `indices[0]`.
The `distances` matrix is of the same shape and contains the distances to those nearest neighbours.
