### ISSUE TITLE
Storing and loading the trained model 

### ISSUE THREAD

**Issue by sjschmid** [x-tabdeveloping/neofuzz#3]
It would be very nice if the trained model could be stored and reloaded for later use.

**Comment by x-tabdeveloping** [comment]
Thanks for the issue! I suppose I forgot to write about it in the documentation, but you can easily use joblib for serializing models just like in scikit-learn.
I can add a page to the docs about this or even some methods if you think that would be satisfactory.

**Comment by sjschmid** [comment]
That would be great! Thanks in advance.

**Comment by x-tabdeveloping** [comment]
Added both a page and methods! Try version `0.2.0` :D
