### ISSUE TITLE
Process.from_disk throws TypeError: too many positional arguments

### ISSUE THREAD

**Issue by AdiGro** [x-tabdeveloping/neofuzz#7]
I am trying to load pretrained data using `Process.from_disk(filename)` but it throws a TypeError
Full traceback: https://basedbin.fly.dev/p/odbTJx.py

**Comment by x-tabdeveloping** [comment]
Can you reproduce the error somehow or give me some code examples?

**Comment by AdiGro** [comment]
Sure! Have a look at this [gist](https://gist.github.com/AdiGro/555f10bd38bf2dc53771a53631420566)

**Comment by x-tabdeveloping** [comment]
Thanks! It seems to me that there must be some issue with pickling PyNNDescent objects, I will look into this.

**Comment by AdiGro** [comment]
Yes, thank you for your response. I tried downgrading the library to an older version and it worked fine. You can have a look [here](https://gist.github.com/AdiGro/18e9ddd4402e90e8871f75a0b2b42066).
I could PR and change the dependency version if you'd like.

**Comment by x-tabdeveloping** [comment]
I'd really appreciate that actually, thanks

**Comment by x-tabdeveloping** [comment]
I have merged your PR and published the new version. Thanks for your time :D I'm closing the issue
